### ISSUE TITLE
Do the double guillemets become part of the identifier name?

### ISSUE THREAD

**Issue by nielsvoss** [leanprover/reference-manual#191]
**Describe the error**

In [3.1.1.2.3. Keywords and Identifiers](https://lean-lang.org/doc/reference/latest/find/?domain=Verso.Genre.Manual.section&name=keywords-and-identifiers):

> Identifiers components may also be surrounded by double guillemets ('«' and '»'). Such identifier components may contain any character at all, aside from '»', even '«' and newlines.

Why is it incorrect and/or confusing?

I think it's unclear if the double guillemets become part of the identifier name, or if they just act as a way to let you write identifiers that might involve reserved keywords or illegal characters (like backticks in Kotlin). Basically, do `«apple»` and `apple` mean different things?

Also a minor nitpick: not sure if there should be a comma between "all" and "aside". Also, is it really true that _all_ characters are legal, including things like non-printing characters, control characters, RTL marks, null bytes, EOF characters, etc.?

**Comment by david-christiansen** [comment]
These are very good questions that need to be addressed, but part of addressing it may be a patch to the parser to help it remain clear. I'll follow up - thanks!

**Comment by david-christiansen** [comment]
This is fixed in #191. 

Yes, it really does allow control characters and null characters. EOF isn't really a character, but there are now tests that check this. I don't want to advertise it all that much, though, because I think we may want to restrict the a little bit, so I think the current accurate-yet-not-calling-out-scary-features description is OK.
